# Generated by Django 4.2.4 on 2023-10-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_merchant_id_order_payment_intent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
